[theme]
#primaryColor="#000000"
#backgroundColor="#FFFFFF"
#secondaryBackgroundColor="#A7C7E7"
#textColor="#000000"
#font="sans serif"

primaryColor="#FF0000"
backgroundColor="#FFFFFF"
secondaryBackgroundColor="#BCBCBC"
textColor="#000000"
font="sans serif"
